#define FOR(VAR,MAX) for(VAR=0;VAR<MAX;VAR++)
#define FOR_1(VAR,MAX) for(VAR=1;VAR<MAX;VAR++)
#define FOR_STEP(VAR,MAX,INC) for(VAR=0;VAR<MAX;VAR+=INC)
#define FOR_START(VAR,MIN,MAX) for(VAR=MIN;VAR<MAX;VAR++)
#define FOR_START_STEP(VAR,MIN,MAX,INC) for(VAR=MIN;VAR<MAX;VAR+=INC)

#define FOR_DEC(VAR,START) for(VAR=START;VAR>=0;VAR--)
#define FOR_DEC_1(VAR,START) for(VAR=START;VAR>0;VAR--)
