#define TENSOR_CHANNEL_POINTER(PTR,C) (PTR->data + (((PTR->h)*(PTR->w))*C))
#define SELECT_TENSOR_CHANNEL(PTR,C) {PTR->w,PTR->h,TENSOR_CHANNEL_POINTER(PTR,C)}

//#define MATRIX_TO_TENSOR(MPTR,TPTR,LAYER) FOR(TPTR->h) FOR(TPTR->w) ...
